name: Build python app

on:
  push:
    branches: main

env:
  APP_NAME: ${{ values.app_name }}
  GCP_PROJECT_ID: ${{ values.project_id }}
  REPO_NAME: terraform-${{ values.app_name }}

{% raw %}
jobs:
  build-fastapi-app:
    name: Build FastAPI App
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      actions: read
      checks: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          pip install -r fast-api-skeleton/content/requirements.txt
          pip install pytest

      - name: Unit Tests
        uses: pavelzw/pytest-action@v2
        continue-on-error: true
        with:
          verbose: true
          emoji: false
          job-summary: true
          custom-arguments: '-q'
          click-to-expand: false
          report-title: 'Unit Tests Report'

      - name: Git Leaks - Scanning for passwords, tokens, etc.
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

      - name: Sonar Scan
        run: echo "Run SonarQube scan"

      - name: configure gcp credentials
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: auth docker
        run: gcloud --quiet auth configure-docker us-east4-docker.pkg.dev
      
      - name: Build and push
        run: |
          docker build --tag "us-east4-docker.pkg.dev/png-gcp-learning-poc/python-fastapi/${{ env.APP_NAME }}:${{github.run_number}}" .
      
      - name: Push to artifact registry
        run: |
          docker push us-east4-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/python-fastapi/${{ env.APP_NAME }}:${{github.run_number}}
          gcloud container images add-tag us-east4-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/python-fastapi/${{ env.APP_NAME }}:${{github.run_number}} us-east4-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/python-fastapi/${{ env.APP_NAME }}:latest

      - name: Call CD workflow
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ORG_GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/monkmantra/${{ env.REPO_NAME }}/dispatches" -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'
{% endraw %}  
